@extends('layouts.app')
@section('title',$product->name.' — CotaSmart')
@section('content')
<a class="back" href="{{ route('app.dashboard') }}">← Voltar para consultas</a>
<div class="product-detail content-block"><div class="detail-image">{{ strtoupper(substr($product->brand?->name ?? 'CS',0,2)) }}</div><div><span class="kicker">{{ strtoupper($product->category?->name ?? 'PRODUTO') }}</span><h1>{{ $product->name }}</h1><p>{{ $product->brand?->name }} · {{ $product->model }}</p><p>{{ $product->description }}</p>@if($product->specifications)<div class="specs">@foreach($product->specifications as $key=>$value)<div><span>{{ str_replace('_',' ',$key) }}</span><strong>{{ $value }}</strong></div>@endforeach</div>@endif</div></div>
<div class="two-columns"><section class="content-block"><div class="block-head"><div><h2>Histórico de preço</h2><p>Valores registrados ao longo do tempo.</p></div></div><canvas id="priceChart" height="250"></canvas></section><aside class="content-block"><span class="kicker">MELHOR OFERTA</span>@if($product->offers->first())<div class="big-price">R$ {{ number_format($product->offers->first()->current_price,2,',','.') }}</div><p>{{ $product->offers->count() }} oferta(s) disponível(is).</p>@else<p>Nenhuma oferta disponível.</p>@endif</aside></div>
<section class="content-block"><div class="block-head"><div><h2>Ofertas disponíveis</h2><p>Compare também frete e condição de pagamento.</p></div></div><div class="table-wrap"><table><thead><tr><th>Fonte</th><th>Preço</th><th>Frete</th><th>Total</th><th>Atualização</th><th></th></tr></thead><tbody>@forelse($product->offers as $offer)<tr><td>{{ $offer->source->name }}</td><td>R$ {{ number_format($offer->current_price,2,',','.') }}</td><td>R$ {{ number_format($offer->shipping_price ?? 0,2,',','.') }}</td><td><strong>R$ {{ number_format($offer->current_price+($offer->shipping_price??0),2,',','.') }}</strong></td><td>{{ $offer->last_checked_at?->format('d/m/Y H:i') }}</td><td><a class="btn outline" href="{{ $offer->url }}" target="_blank" rel="noopener">Abrir fonte</a></td></tr>@empty<tr><td colspan="6">Nenhuma oferta válida.</td></tr>@endforelse</tbody></table></div></section>
@endsection
@push('scripts')<script>window.priceHistory=@json($chartData);</script><script src="{{ asset('js/price-chart.js') }}"></script>@endpush

